<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\MelonLoader\net6\**\*.dll" Private="false" />
		<Reference Include="C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\MelonLoader\net35\**\*.dll" Private="false" />
		<Reference Include="C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\MelonLoader\Il2CppAssemblies\**\*.dll" Private="false" />
		<Reference Include="C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\Mods\ReplayMod.dll" Private="false" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="assets\AssetBundles - Shortcut.lnk" />
	  <None Remove="assets\replaystudio" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="assets\replaystudio" />
	</ItemGroup>

	<Target Name="PreBuild" AfterTargets="PreBuildEvent">
		<Exec Command="taskkill /f /t /im RUMBLE.exe 2>NUL | echo killed rumble" />
	</Target>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy &quot;$(TargetPath)&quot; &quot;C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\Mods\$(TargetFileName)&quot;" />
	</Target>

</Project>
